on:
  push:
    branches:
      - "development"
  schedule:
    - cron:  '0 0 * * *'

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        curl -X GET https://raw.githubusercontent.com/MKS-Dashboard/datafiles/main/additionalvalues.json > datafiles/additionalvalues.json
        curl -X GET https://raw.githubusercontent.com/MKS-Dashboard/datafiles/main/buildings.json > datafiles/buildings.json
        curl -X GET https://raw.githubusercontent.com/MKS-Dashboard/datafiles/main/games.json > datafiles/games.json
        curl -X GET https://raw.githubusercontent.com/MKS-Dashboard/datafiles/main/vehiclegroups.json > datafiles/vehiclegroups.json
        curl -X GET https://raw.githubusercontent.com/MKS-Dashboard/datafiles/main/vehicles.json > datafiles/vehicles.json
        
    - name: Prettify code
      uses: creyD/prettier_action@v3.3
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
